version: '3.3'
services:
    openbullet2:
        restart: unless-stopped
        ports:
            - '8069:5000'
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
        volumes:
            - './UserData:/app/UserData' # Corrected volume format
        image: 'openbullet/openbullet2:latest'

    # Watchtower will auto update OB2 for you when it sees a new release
    watchtower:
        image: containrrr/watchtower
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /etc/timezone:/etc/timezone:ro
        environment:
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_LABEL_ENABLE=true
            - WATCHTOWER_INCLUDE_RESTARTING=true
        labels:
            - "com.centurylinklabs.watchtower.enable=true"

volumes:
    UserData:
